### ISSUE TITLE
Issue when deleting temporal entity information

### ISSUE THREAD

**Issue by Jxlle** [wistefan/mintaka#160]
Hi,

I tried to delete the temporal information for one of my entities:
`DELETE .../temporal/entities/urn:ngsi-ld:Transport:001`

But I got the following error message:
```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/OperationNotSupported",
    "title": "Method is not supported.",
    "status": 422,
    "detail": "Method Not Allowed"
}
```

Furthermore, deleting attributes seems to return a `NOT FOUND`. The `DELETE` endpoint was retrieved from the API docs: https://github.com/FIWARE/mintaka/blob/main/api/full_api.yaml

Am I doing something wrong, or is this a bug? 

**Side note**: Executing
`GET .../temporal/entities/urn:ngsi-ld:Transport:001?timeproperty=modifiedAt`
returns the temporal data as expected.

**Comment by Jonathanroyascanio** [comment]
I have the same bug anyone has updates on this issue ?

**Comment by wistefan** [comment]
Hi, sorry for the inconvience in the doc, but all modifying operations have to go through orion-ld. Mintaka only supports the read-operations.
Best,
Stefan
